### PR TITLE
UI for proof test with cid

### PR DESCRIPTION
**Pull request by Tbaut**
This is a simple UI with relatively helpful messages if:
- the api can't connect to the node, e.g the node isn't started
- the user doesn't have the polkadot extension installed, or if they have no account
- if the node throws error at the proof verification, we display them (see demo below)

For now the wallet account is useless since there is nothing that needs to be signed.

https://user-images.githubusercontent.com/33178835/148461351-d7a1e1c0-9016-4f29-90ea-812ce9bd8274.mp4

### CODE REVIEW

**Review by clearloop — APPROVED** [review]
lgtm! tested on my local machine!

**Review by mattsse — APPROVED** [review]
this looks great!

**Comment by Tbaut** [comment]
@clearloop what is lerna used for? Did you set it up so that you can use any package locally without needing them to be published?
I'm happy to explore this in another PR, not sure how much it would break :D

**Comment by clearloop** [comment]
> Did you set it up so that you can use any package locally without needing them to be published?

yarn workspace already supported this feature, once you made `/ui` a member of `/package.json`, you can build `@chiansafe/filecoindot-types` locally but not from the registry

https://classic.yarnpkg.com/lang/en/docs/workspaces/#toc-how-does-it-compare-to-lerna

currently `lerna` is just for the shortcut of running `yarn build` for each packages in `/js`, as a preprocess for publishing packages to the npm registry

https://github.com/ChainSafe/filecoindot/blob/7efe1430b6b2b1763fd0ab17473d55eee10e0182/package.json#L15-L20

also, we can use lerna to do the version control stuff for our javascript packages in the future

> I'm happy to explore this in another PR, not sure how much it would break :D

mb you can try to play with the version control stuff with lerna LOL, it's really a tough topic in javascript package management I think, and lerna is also hard to control in my past experience...

**Comment by Tbaut** [comment]
yarn workspace is what I've seen used the most indeed, and ppl, just like you mentioned were avoiding lerna as much as possible.
I won't play with yarn workspace immediately, because things work so far, but I'll keep this in mind for the future eventually.

**Pull request merged**
